apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: openshift-kie
    version: v1
  name: openshift-kie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openshift-kie
      version: v1
  template:
    metadata:
      labels:
        app: openshift-kie
        version: v1
    spec:
      containers:
        - env:
          image: quickstarter/openshift-kie:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - curl
                - localhost:8080/rest/health
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
          name: quick-drools
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - curl
                - localhost:8080/rest/health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
          securityContext:
            privileged: false
