apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: openshift-kie-thorntail
    version: v1
  name: openshift-kie-thorntail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openshift-kie-thorntail
      version: v1
  template:
    metadata:
      labels:
        app: openshift-kie-thorntail
        version: v1
    spec:
      containers:
        - env:
          - name: KAFKA_EXTERNAL_ADDRESSES
            value: my-cluster-kafka-external-bootstrap.my-kafka-project.svc
          - name: KAFKA_BOOTSTRAP
            value: my-cluster-kafka-bootstrap.my-kafka-project.svc
          image: quickstarter/openshift-kie-thorntail:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - curl
                - localhost:8080/rest/health
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
          name: quick-drools
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - curl
                - localhost:8080/rest/health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
          securityContext:
            privileged: false
